### ISSUE TITLE
Problem with defpymodule

### ISSUE THREAD

**Issue by simenjh** [digikar99/py4cl2#17] opened 2022-06-25 19:31 UTC
I have Windows 11 SBCL and Python 3.10.5.

From Slime I try to run the example: 

```
(ql:quickload :py4cl2 :silent t)

(py4cl2:defpymodule "numpy" nil :lisp-package "NP")
(py4cl2:defpymodule "scipy.integrate" nil :lisp-package "INTEGRATE")

;; Integrate some ODEs
(defparameter *data*
  (integrate:odeint 
   :func (lambda (y time) 
           (list (aref y 1)       ; dy[0]/dt = y[1]
                 (- (aref y 0)))) ; dy[1]/dt = -y[0]
   :y-0 #(1.0 0.0)   ; Initial state
   :t (np:linspace :start 0.0 :stop (* 2 pi) :num 20)))
```

But then I get the error: 

> Symbol "ODEINT" not found in the INTEGRATE package.

The same goes for linspace in np. 

Both numpy and scipy are installed.

I want to try out some machine learning, so I have also installed tensorflow and keras. 
It finds the keras library, because this works:
```
(defpyfun "Input" "keras.layers" :lisp-fun-name "INP")
(inp :shape '(1 2))
```

but 
```
(defpymodule "keras.layers" t :lisp-package "KL")
```
produces

2022-06-25 21:30:20.080513: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-06-25 21:30:20.080700: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Defining KL for accessing python package kl..
Defining KL.ACTIVATION for accessing python package kl.activation..
Defining KL.ACTIVATION.ELU for accessing python package kl.activation.elu..
Defining KL.ACTIVATION.LEAKY-RELU for accessing python package kl.activation.leaky_relu..
Defining KL.ACTIVATION.PRELU for accessing python package kl.activation.prelu..
Defining KL.ACTIVATION.RELU for accessing python package kl.activation.relu..
Defining KL.ACTIVATION.SOFTMAX for accessing python package kl.activation.softmax..
Defining KL.ACTIVATION.THRESHOLDED-RELU for accessing python package kl.activation.thresholded_relu..
Defining KL.ATTENTION for accessing python package kl.attention..
Defining KL.ATTENTION.ADDITIVE-ATTENTION for accessing python package kl.attention.additive_attention..
Defining KL.ATTENTION.ATTENTION for accessing python package kl.attention.attention..
Defining KL.ATTENTION.BASE-DENSE-ATTENTION for accessing python package kl.attention.base_dense_attention..
Defining KL.ATTENTION.MULTI-HEAD-ATTENTION for accessing python package kl.attention.multi_head_attention..
Defining KL.CONVOLUTIONAL for accessing python package kl.convolutional..
Defining KL.CONVOLUTIONAL.BASE-CONV for accessing python package kl.convolutional.base_conv..
Defining KL.CONVOLUTIONAL.BASE-DEPTHWISE-CONV for accessing python package kl.convolutional.base_depthwise_conv..
Defining KL.CONVOLUTIONAL.BASE-SEPARABLE-CONV for accessing python package kl.convolutional.base_separable_conv..
Defining KL.CONVOLUTIONAL.CONV-1D for accessing python package kl.convolutional.conv_1d..
Defining KL.CONVOLUTIONAL.CONV-2D for accessing python package kl.convolutional.conv_2d..
Defining KL.CONVOLUTIONAL.CONV-3D-TRANSPOSE for accessing python package kl.convolutional.conv_3d_transpose..
Defining KL.CONVOLUTIONAL.SEPARABLE-CONV-1D for accessing python package kl.convolutional.separable_conv_1d..

and the error:

> Unhandled message type '
> '
>    [Condition of type SIMPLE-ERROR]
> 
> Restarts:
>  0: [CONTINUE-IGNORING-ERRORS] PY4CL2::CONTINUE-IGNORING-ERRORS
>  1: [CONTINUE-IGNORING-ERRORS] PY4CL2::CONTINUE-IGNORING-ERRORS
>  2: [RETRY] Retry SLIME REPL evaluation request.
>  3: [*ABORT] Return to SLIME's top level.
>  4: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1004079953}>)
> 
> Backtrace:
>   0: (PY4CL2::DISPATCH-MESSAGES #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {10030E1023}>)
>   1: (RAW-PYEXEC "import inspect")
>   2: (PY4CL2::DEFPYFUN* "AveragePooling1D" "kl.convolutional" "AveragePooling1D" "AVERAGE-POOLING-1D/CLASS" #<PACKAGE "KL.CONVOLUTIONAL"> T)
>   3: (PY4CL2::DEFPYMODULE* "kl.convolutional" T "KL.CONVOLUTIONAL" T T T T NIL)
>   4: ((MACRO-FUNCTION DEFPYMODULE) (DEFPYMODULE "kl.convolutional" T :CACHE T :LISP-PACKAGE ...) #<unused argument>)
>   5: (MACROEXPAND-1 (DEFPYMODULE "kl.convolutional" T :CACHE T :LISP-PACKAGE ...) NIL)
>   6: (PY4CL2::DEFPYSUBMODULES "kl" "KL" T)
>   7: (PY4CL2::DEFPYMODULE* "keras.layers" T "KL" T T T T NIL)
>   8: ((MACRO-FUNCTION DEFPYMODULE) (DEFPYMODULE "keras.layers" T :LISP-PACKAGE "KL") #<unused argument>)
>   9: (MACROEXPAND-1 (DEFPYMODULE "keras.layers" T :LISP-PACKAGE "KL") #<NULL-LEXENV>)
>  10: (MACROEXPAND (DEFPYMODULE "keras.layers" T :LISP-PACKAGE "KL") #<NULL-LEXENV>)
>  11: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DEFPYMODULE "keras.layers" T :LISP-PACKAGE "KL") #<NULL-LEXENV>)
>  12: (EVAL (DEFPYMODULE "keras.layers" T :LISP-PACKAGE "KL"))
>  --more--
> 

or sometimes 

> Unhandled message type '
> '
>    [Condition of type SIMPLE-ERROR]
> 
> Restarts:
>  0: [CONTINUE-IGNORING-ERRORS] PY4CL2::CONTINUE-IGNORING-ERRORS
>  1: [CONTINUE-IGNORING-ERRORS] PY4CL2::CONTINUE-IGNORING-ERRORS
>  2: [RETRY] Retry SLIME REPL evaluation request.
>  3: [*ABORT] Return to SLIME's top level.
>  4: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1004069953}>)
> 
> Backtrace:
>   0: (PY4CL2::DISPATCH-MESSAGES #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {10030E9203}>)
>   1: (RAW-PYEXEC "import inspect")
>   2: (PY4CL2::DEFPYFUN* "AveragePooling1D" "kl.convolutional" "AveragePooling1D" "AVERAGE-POOLING-1D/CLASS" #<PACKAGE "KL.CONVOLUTIONAL"> T)
>   3: (PY4CL2::DEFPYMODULE* "kl.convolutional" T "KL.CONVOLUTIONAL" T T T T NIL)
>   4: ((MACRO-FUNCTION DEFPYMODULE) (DEFPYMODULE "kl.convolutional" T :CACHE T :LISP-PACKAGE ...) #<unused argument>)
>   5: (MACROEXPAND-1 (DEFPYMODULE "kl.convolutional" T :CACHE T :LISP-PACKAGE ...) NIL)
>   6: (PY4CL2::DEFPYSUBMODULES "kl" "KL" T)
>   7: (PY4CL2::DEFPYMODULE* "keras.layers" T "KL" T T T T NIL)
>   8: ((MACRO-FUNCTION DEFPYMODULE) (DEFPYMODULE "keras.layers" T :LISP-PACKAGE "KL") #<unused argument>)
>   9: (MACROEXPAND-1 (DEFPYMODULE "keras.layers" T :LISP-PACKAGE "KL") #<NULL-LEXENV>)
>  10: (MACROEXPAND (DEFPYMODULE "keras.layers" T :LISP-PACKAGE "KL") #<NULL-LEXENV>)
>  11: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DEFPYMODULE "keras.layers" T :LISP-PACKAGE "KL") #<NULL-LEXENV>)
>  12: (EVAL (DEFPYMODULE "keras.layers" T :LISP-PACKAGE "KL"))
>  --more--

**Comment by simenjh** [comment] 2022-06-25 19:35
Hmm, now `(defpyfun "Input" "keras.layers" :lisp-fun-name "INP")`
produces

Python error: Traceback (most recent call last):

  File "C:\Users\Simen\quicklisp\dists\quicklisp\software\py4cl2-v2.9.0\py4cl.py", line 407, in message_dispatch_loop

    result = eval(expr, eval_globals)

  File "<string>", line 1, in <module>

TypeError: 'NoneType' object is not iterable

   [Condition of type PYERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1004079953}>)

Backtrace:
  0: (PY4CL2::DISPATCH-MESSAGES #<UIOP/LAUNCH-PROGRAM::PROCESS-INFO {10030E1023}>)
  1: (RAW-PYEXEC "import inspect")
  2: (PY4CL2::DEFPYFUN* "Input" "keras.layers" "Input" "INP" #<PACKAGE "COMMON-LISP-USER"> T)
  3: (MACROEXPAND-1 (DEFPYFUN "Input" "keras.layers" :LISP-FUN-NAME "INP") #<NULL-LEXENV>)
  4: (MACROEXPAND (DEFPYFUN "Input" "keras.layers" :LISP-FUN-NAME "INP") #<NULL-LEXENV>)
  5: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DEFPYFUN "Input" "keras.layers" :LISP-FUN-NAME "INP") #<NULL-LEXENV>)
  6: (EVAL (DEFPYFUN "Input" "keras.layers" :LISP-FUN-NAME "INP"))
 --more--

**Comment by digikar99** [comment] 2022-06-26 02:59
I just tested it with python 3.10.5, and the examples above are completely fine on Linux.

On Windows, I am able to confirm the issue with py4cl2 v2.9.0 (latest). Things work fine with v2.8.0. Hoping to issue a fix soon!

**Comment by digikar99** [comment] 2022-06-26 10:03
The issue was caused due to incorrect handling of carriage-returns and newlines on windows. For some reason, this only showed up after the recent addition of printing tracebacks. The errors also disappear after `(setf (config-var 'print-python-traceback) nil)` (and restarting the python process - or the lisp itself :/).

I've issued attempted a fix, and I no longer get the above errors on windows even if  `(setf (config-var 'print-python-traceback) t)`. But, I'm still unable to test it locally because of random freezes that I've been unable to debug.

Let me know if the error still persists!

**Comment by simenjh** [comment] 2022-06-26 10:46
I can confirm that it's working both after `(setf (config-var 'print-python-traceback) nil)` and `(setf (config-var 'print-python-traceback) t)`. Thanks for fixing this so quickly!

**Comment by simenjh** [comment] 2022-06-26 11:07
Although, it produces an error when importing tensorflow: 
```
CL-USER> (defpymodule "tensorflow" t :lisp-package "TF")
Defining TF for accessing python package tf..
Defining TF.SUMMARY for accessing python package tf.summary..
```

produces

> The value
>   "()"
> is not of type
>   LIST
>    [Condition of type TYPE-ERROR]
> 
> Restarts:
>  0: [CONTINUE-IGNORING-ERRORS] PY4CL2::CONTINUE-IGNORING-ERRORS
>  1: [CONTINUE-IGNORING-ERRORS] PY4CL2::CONTINUE-IGNORING-ERRORS
>  2: [RETRY] Retry SLIME REPL evaluation request.
>  3: [*ABORT] Return to SLIME's top level.
>  4: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1004079953}>)
> 
> Backtrace:
>   0: (PY4CL2::DEFPYSUBMODULES "tf.summary" "TF.SUMMARY" T)
>   1: (PY4CL2::DEFPYMODULE* "tf.summary" T "TF.SUMMARY" T T T T NIL)
>   2: ((MACRO-FUNCTION DEFPYMODULE) (DEFPYMODULE "tf.summary" T :CACHE T :LISP-PACKAGE ...) #<unused argument>)
>   3: (MACROEXPAND-1 (DEFPYMODULE "tf.summary" T :CACHE T :LISP-PACKAGE ...) NIL)
>   4: (PY4CL2::DEFPYSUBMODULES "tf" "TF" T)
>   5: (PY4CL2::DEFPYMODULE* "tensorflow" T "TF" T T T T NIL)
>   6: ((MACRO-FUNCTION DEFPYMODULE) (DEFPYMODULE "tensorflow" T :LISP-PACKAGE "TF") #<unused argument>)
>   7: (MACROEXPAND-1 (DEFPYMODULE "tensorflow" T :LISP-PACKAGE "TF") #<NULL-LEXENV>)
>   8: (MACROEXPAND (DEFPYMODULE "tensorflow" T :LISP-PACKAGE "TF") #<NULL-LEXENV>)
>   9: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DEFPYMODULE "tensorflow" T :LISP-PACKAGE "TF") #<NULL-LEXENV>)
>  10: (EVAL (DEFPYMODULE "tensorflow" T :LISP-PACKAGE "TF"))
>  --more--

**Comment by digikar99** [comment] 2022-06-26 14:31
It should be fixed now.

**Comment by simenjh** [comment] 2022-06-26 17:18
Now it just hangs at 

> CL-USER> (defpymodule "tensorflow" t :lisp-package "TF")
> 2022-06-26 17:17:28.085162: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
> 2022-06-26 17:17:28.085279: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> Defining TF for accessing python package tf..
> Defining TF.KERAS for accessing python package tf.keras..
> Defining TF.KERAS.ACTIVATIONS for accessing python package tf.keras.activations..
> Defining TF.KERAS.APPLICATIONS for accessing python package tf.keras.applications..
> Defining TF.KERAS.APPLICATIONS.DENSENET for accessing python package tf.keras.applications.densenet..
> Defining TF.KERAS.APPLICATIONS.EFFICIENTNET for accessing python package tf.keras.applications.efficientnet..
> Defining TF.KERAS.APPLICATIONS.EFFICIENTNET-V-2 for accessing python package tf.keras.applications.efficientnet_v_2..
> Defining TF.KERAS.APPLICATIONS.IMAGENET-UTILS for accessing python package tf.keras.applications.imagenet_utils..
> Defining TF.KERAS.APPLICATIONS.INCEPTION-RESNET-V-2 for accessing python package tf.keras.applications.inception_resnet_v_2..
> Defining TF.KERAS.APPLICATIONS.INCEPTION-V-3 for accessing python package tf.keras.applications.inception_v_3..
> Defining TF.KERAS.APPLICATIONS.MOBILENET for accessing python package tf.keras.applications.mobilenet..
> Defining TF.KERAS.APPLICATIONS.MOBILENET-V-2 for accessing python package tf.keras.applications.mobilenet_v_2..
> Defining TF.KERAS.APPLICATIONS.MOBILENET-V-3 for accessing python package tf.keras.applications.mobilenet_v_3..
> Defining TF.KERAS.APPLICATIONS.NASNET for accessing python package tf.keras.applications.nasnet..
> Defining TF.KERAS.APPLICATIONS.REGNET for accessing python package tf.keras.applications.regnet..
> Defining TF.KERAS.APPLICATIONS.RESNET for accessing python package tf.keras.applications.resnet..
> Defining TF.KERAS.APPLICATIONS.RESNET-50 for accessing python package tf.keras.applications.resnet_50..
> Defining TF.KERAS.APPLICATIONS.RESNET-RS for accessing python package tf.keras.applications.resnet_rs..
> Defining TF.KERAS.APPLICATIONS.RESNET-V-2 for accessing python package tf.keras.applications.resnet_v_2..
> Defining TF.KERAS.APPLICATIONS.VGG-16 for accessing python package tf.keras.applications.vgg_16..
> Defining TF.KERAS.APPLICATIONS.VGG-19 for accessing python package tf.keras.applications.vgg_19..
> Defining TF.KERAS.APPLICATIONS.XCEPTION for accessing python package tf.keras.applications.xception..
> Defining TF.KERAS.BACKEND for accessing python package tf.keras.backend..
> Defining TF.KERAS.BACKEND.EXPERIMENTAL for accessing python package tf.keras.backend.experimental..
> Defining TF.KERAS.CALLBACKS for accessing python package tf.keras.callbacks..
> Defining TF.KERAS.CALLBACKS.EXPERIMENTAL for accessing python package tf.keras.callbacks.experimental..
> Defining TF.KERAS.CONSTRAINTS for accessing python package tf.keras.constraints..
> Defining TF.KERAS.DATASETS for accessing python package tf.keras.datasets..
> Defining TF.KERAS.DATASETS.BOSTON-HOUSING for accessing python package tf.keras.datasets.boston_housing..
> Defining TF.KERAS.DATASETS.CIFAR-10 for accessing python package tf.keras.datasets.cifar_10..
> Defining TF.KERAS.DATASETS.CIFAR-100 for accessing python package tf.keras.datasets.cifar_100..
> Defining TF.KERAS.DATASETS.FASHION-MNIST for accessing python package tf.keras.datasets.fashion_mnist..
> Defining TF.KERAS.DATASETS.IMDB for accessing python package tf.keras.datasets.imdb..
> Defining TF.KERAS.DATASETS.MNIST for accessing python package tf.keras.datasets.mnist..
> Defining TF.KERAS.DATASETS.REUTERS for accessing python package tf.keras.datasets.reuters..
> Defining TF.KERAS.DTENSOR for accessing python package tf.keras.dtensor..
> Defining TF.KERAS.DTENSOR.EXPERIMENTAL for accessing python package tf.keras.dtensor.experimental..
> Defining TF.KERAS.DTENSOR.EXPERIMENTAL.OPTIMIZERS for accessing python package tf.keras.dtensor.experimental.optimizers..
> Defining TF.KERAS.ESTIMATOR for accessing python package tf.keras.estimator..
> Defining TF.KERAS.EXPERIMENTAL for accessing python package tf.keras.experimental..
> Defining TF.KERAS.INITIALIZERS for accessing python package tf.keras.initializers..
> Defining TF.KERAS.LAYERS for accessing python package tf.keras.layers..
> Defining TF.KERAS.LAYERS.EXPERIMENTAL for accessing python package tf.keras.layers.experimental..
> Defining TF.KERAS.LAYERS.EXPERIMENTAL.PREPROCESSING for accessing python package tf.keras.layers.experimental.preprocessing..
> Defining TF.KERAS.LOSSES for accessing python package tf.keras.losses..

without getting any further...

**Comment by digikar99** [comment] 2022-06-29 02:45
Is this still an issue? Things do seem to work fine on Linux. I'll need to check on Windows.

**Comment by jcguu95** [comment] 2022-11-12 19:28
@simenjh is this still an issue?

**Comment by digikar99** [comment] 2022-12-20 09:13
With dfbb2ef9e457f15cccf16418270f252fcfcabd33 I can confirm that all the commands work without freezing or errors.

```lisp
(ql:quickload :py4cl2 :silent t)

(py4cl2:defpymodule "numpy" nil :lisp-package "NP")
(py4cl2:defpymodule "scipy.integrate" nil :lisp-package "INTEGRATE")

;; Integrate some ODEs
(defparameter *data*
  (integrate:odeint 
   :func (lambda (y time) 
           (list (aref y 1)       ; dy[0]/dt = y[1]
                 (- (aref y 0)))) ; dy[1]/dt = -y[0]
   :y-0 #(1.0 0.0)   ; Initial state
   :t (np:linspace :start 0.0 :stop (* 2 pi) :num 20)))

(py4cl2:defpyfun "Input" "keras.layers" :lisp-fun-name "INP")
(inp :shape '(1 2))

(py4cl2:defpymodule "keras.layers" t :lisp-package "KL")
```

Although, this was with python3.9 and its modules all installed through miniconda3. At the time of this writing, python3.9 was the latest that was packaged with miniconda3.

***

I can also confirm that all the py4cl2-tests pass on windows as of the above commit.

**Closed by digikar99** 2022-12-20 09:13 UTC
